name: Syntax Checks

on: [ push, pull_request, workflow_dispatch ]

jobs:
  syntax-checks:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        php: ["7.4", "8.0", "8.1", "8.2", "8.3"]

    name: Syntax Checks Under PHP ${{ matrix.php }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Run Syntax Checks
        run: docker run -q --rm -v "$(pwd):/project" -w /project -i jakzal/phpqa:php${{ matrix.php }} phplint src
